### ISSUE TITLE
matching IDs in folder names

### ISSUE THREAD

**Issue by bison529** [RatingPosterDB/rpdb-folders#10]
Hi,

you mention in last update this point:
- Support matching IDs in folder names, this matching type guarantees 100% perfect matches (examples: [tmdb-x], {tmdb-x}, [tvdb-x], {tvdb-x}, [imdb-x], {imdb-x}, etc)

it's now working with me:
Matched Starstruck (2021) [tvdb-401112] by TVDB ID in folder name
No poster available for Starstruck (2021) [tvdb-401112]

i have used Windows RPDB Folders v0.1.2 .

**Comment by jaruba** [comment]
Hi, thank you for reporting this. I found the underlying issue, it is related to TVDB IDs in particular.

**Comment by jaruba** [comment]
@bison529 

I investigated this a bit more, it seems that there is no issue with TVDB ID matching, the issue was with the poster not being available. This was caused due to a limitation in scanning during the switch to TMDB posters.

The missing poster for Starstruck (2021) has been added and other posters with low number of votes should also become available by tomorrow.

The issue would of also corrected itself by next week, but I set it as a priority task to ensure it gets solved faster.

Thank you again for reporting this.
