### ISSUE TITLE
Feature Request: Skip not found movies for 30/60/90 days

### ISSUE THREAD

**Issue by edrock200** [RatingPosterDB/rpdb-folders#38]
*edit* title should have been "Skip not found movies/TV shows for 30/60/90 days* *endEdit*
Me again.  :) Feature request for your consideration - upon full scan, if a poster can't be matched/found, log it, and allow a configurable "skip on full scans for 30/60/90 days" option. The reason being, I have a very very large library. And on each full scan, I burn through several thousand API hits for those same titles each time, so would be nice to have it skip those, and guessing would also be beneficial for back end load efficiency on your end as well.

Thanks for your consideration.

**Comment by jaruba** [comment]
> if a poster can't be matched/found, log it

I believe they are already logged, in the Edit Movie Poster / Edit Series Poster search page, there is a dropdown option to show / search through items that failed to download a poster.

The issue I see with this proposal is that it may cause more harm than good. Let's presume that you added some new movies to your library, the app tries to find the posters and for whatever reason cannot. (unlikely, but still possible, especially if the internet connection went down) With this change, even if the poster becomes available within the next few minutes / hours, it would only download it in 30/60/90 days.. But maybe it would still be doable, by checking the folder creation date to attempt to distinguish new items from old items, this would need to be investigated though, I'll try to implement it and see how it goes.

My general plan regarding this issue was to keep optimising and monitoring the service in order to increase the API request limit for all Tiers to the point where the requests for missing posters would be negligible compared to the total requests available. I still believe this might be the cleanest solution.. but it would take quite a lot of time compared to other possible solutions.

**Comment by edrock200** [comment]
Gotcha. Thanks! Now with the trigger feature from *arrs I can reduce the full scans to weekly vs every few days. So that should also help. Thanks again!

**Comment by jaruba** [comment]
@edrock200 I have added such features to v0.2.0, I should explain how they work though:

1. there is a setting to choose what should be considered "new", can be set to 3/6/9 months, this checks the creation date of your media folders and all media folders and based on the setting chooses if the app should always attempt to retry getting images

2. a setting for skipping "old" items that do not have images if they have been tried within the last 30/60/90 days

This should be a good enough solution, i will consider this matter resolved for now, if you think we need to reopen this issue later we can do so.
